attack:
  default: "dict"
  bruteforce:
    timeout: 600
    maxLength: 20
    minLength: 0
    characterSet : "lnu"
  dict:
    wordlist: "wordlists/rockyou.txt"
  algorithm: "sha256"
  salt: ""
gui:
  darkmode: true
  extraInfo: false
path : "."
